import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const modules = [
    // 1. Cascadas Estacionarias (Baterías de planta fijas - Hebei Baigong / ISO 9809-1)
    {
      name: 'Cascada Estacionaria 10x150L',
      type: 'ESTACIONARIA',
      cylinderCount: 10,
      cylinderCapacityLiters: 150.0,
      totalCapacityLiters: 1500.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 273.0,
      minOperatingTempC: -40.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 2450.0,
      maxPayloadKg: 337.5,
      grossWeightKg: 2787.5,
      chassisType: 'Batería Estacionaria Vertical',
      tubeMaterial: '34CrMo4',
      tubeOuterDiameterMm: 356.0,
      tubeLengthMm: 1890.0,
      plugConfiguration: 'SINGLE_PLUG',
      valveManufacturer: 'DK-Lok',
      manufacturingStandard: 'ISO 9809-1:1999',
      certificationAgency: 'Bureau Veritas (BV)',
      designLifeYears: 15,
    },
    {
      name: 'Cascada Estacionaria 12x150L',
      type: 'ESTACIONARIA',
      cylinderCount: 12,
      cylinderCapacityLiters: 150.0,
      totalCapacityLiters: 1800.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 273.0,
      minOperatingTempC: -40.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 2940.0,
      maxPayloadKg: 405.0,
      grossWeightKg: 3345.0,
      chassisType: 'Batería Estacionaria Vertical',
      tubeMaterial: '34CrMo4',
      tubeOuterDiameterMm: 356.0,
      tubeLengthMm: 1890.0,
      plugConfiguration: 'SINGLE_PLUG',
      valveManufacturer: 'DK-Lok',
      manufacturingStandard: 'ISO 9809-1:1999',
      certificationAgency: 'Bureau Veritas (BV)',
      designLifeYears: 15,
    },
    {
      name: 'Cascada Estacionaria 16x150L',
      type: 'ESTACIONARIA',
      cylinderCount: 16,
      cylinderCapacityLiters: 150.0,
      totalCapacityLiters: 2400.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 273.0,
      minOperatingTempC: -40.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 3920.0,
      maxPayloadKg: 540.0,
      grossWeightKg: 4460.0,
      chassisType: 'Batería Estacionaria Vertical',
      tubeMaterial: '34CrMo4',
      tubeOuterDiameterMm: 356.0,
      tubeLengthMm: 1890.0,
      plugConfiguration: 'SINGLE_PLUG',
      valveManufacturer: 'DK-Lok',
      manufacturingStandard: 'ISO 9809-1:1999',
      certificationAgency: 'Bureau Veritas (BV)',
      designLifeYears: 15,
    },
    {
      name: 'Cascada Estacionaria 10x125L',
      type: 'ESTACIONARIA',
      cylinderCount: 10,
      cylinderCapacityLiters: 125.0,
      totalCapacityLiters: 1250.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 273.0,
      minOperatingTempC: -40.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 2150.0,
      maxPayloadKg: 281.0,
      grossWeightKg: 2431.0,
      chassisType: 'Batería Estacionaria Vertical',
      tubeMaterial: '34CrMo4',
      tubeOuterDiameterMm: 356.0,
      tubeLengthMm: 1650.0,
      plugConfiguration: 'SINGLE_PLUG',
      valveManufacturer: 'DK-Lok',
      manufacturingStandard: 'ISO 9809-1:1999',
      certificationAgency: 'Bureau Veritas (BV)',
      designLifeYears: 15,
    },
    {
      name: 'Cascada Estacionaria 16x125L',
      type: 'ESTACIONARIA',
      cylinderCount: 16,
      cylinderCapacityLiters: 125.0,
      totalCapacityLiters: 2000.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 273.0,
      minOperatingTempC: -40.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 3440.0,
      maxPayloadKg: 450.0,
      grossWeightKg: 3890.0,
      chassisType: 'Batería Estacionaria Vertical',
      tubeMaterial: '34CrMo4',
      tubeOuterDiameterMm: 356.0,
      tubeLengthMm: 1650.0,
      plugConfiguration: 'SINGLE_PLUG',
      valveManufacturer: 'DK-Lok',
      manufacturingStandard: 'ISO 9809-1:1999',
      certificationAgency: 'Bureau Veritas (BV)',
      designLifeYears: 15,
    },

    // 2. Módulos de Transporte (Tráilers Móviles de Carretera - Fichas Técnicas Luxi / ISO 11120)
    {
      name: 'Tráiler Transporte 11 Tubos (26.95 m³)',
      type: 'TRANSPORTE',
      cylinderCount: 11,
      cylinderCapacityLiters: 2450.0,
      totalCapacityLiters: 26950.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 375.0, // Disco de ruptura
      minOperatingTempC: -50.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 32200.0, // Sin chasis
      maxPayloadKg: 6063.0,
      grossWeightKg: 38263.0,
      chassisType: 'Triple eje / Three-axis',
      tubeMaterial: '4130X',
      tubeOuterDiameterMm: 559.0,
      tubeLengthMm: 11580.0,
      plugConfiguration: 'DOUBLE_PLUG',
      valveManufacturer: 'DK-Lok',
      manufacturingStandard: 'ISO 11120:2015',
      certificationAgency: 'Bureau Veritas (BV), ISO',
      designLifeYears: 15,
    },
    {
      name: 'Tráiler Transporte 11 Tubos (25.52 m³)',
      type: 'TRANSPORTE',
      cylinderCount: 11,
      cylinderCapacityLiters: 2320.0,
      totalCapacityLiters: 25520.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 375.0,
      minOperatingTempC: -50.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 28784.0,
      maxPayloadKg: 5742.0,
      grossWeightKg: 34526.0,
      chassisType: 'Triple eje / Three-axis',
      tubeMaterial: '4130X',
      tubeOuterDiameterMm: 559.0,
      tubeLengthMm: 10950.0,
      plugConfiguration: 'DOUBLE_PLUG',
      valveManufacturer: 'DK-Lok',
      manufacturingStandard: 'ISO 11120:2015',
      certificationAgency: 'Bureau Veritas (BV), ISO',
      designLifeYears: 15,
    },
    {
      name: 'Tráiler Transporte 12 Tubos (27.84 m³)',
      type: 'TRANSPORTE',
      cylinderCount: 12,
      cylinderCapacityLiters: 2320.0,
      totalCapacityLiters: 27840.0,
      workingPressureBar: 250.0,
      testPressureBar: 375.0,
      safetyReliefPressureBar: 375.0,
      minOperatingTempC: -50.0,
      maxOperatingTempC: 60.0,
      tareWeightKg: 30540.0,
      maxPayloadKg: 6264.0,
      grossWeightKg: 36814.0,
      chassisType: 'Triple eje / Three-axis',
      tubeMaterial: '4130X',
      tubeOuterDiameterMm: 559.0,
      tubeLengthMm: 10975.0,
      plugConfiguration: 'DOUBLE_PLUG',
      valveManufacturer: 'Parker of USA',
      manufacturingStandard: 'ISO 11120:2015',
      certificationAgency: 'Bureau Veritas (BV), ISO, CE',
      designLifeYears: 15,
    }
  ];

  for (const mod of modules) {
    await prisma.storageModule.upsert({
      where: { name: mod.name },
      update: mod,
      create: mod,
    });
  }
  console.log('Módulos de almacenamiento sembrados exitosamente con fichas técnicas industriales completas.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
